import Image from 'next/image'
import Link from 'next/link'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <main>
      <header className="max-w[1440] mx-auto flex max-w-7xl items-center justify-between py-6 px-4 lg:px-20">
        <Image src="/logo.svg" alt="" width={170} height={42} />
        <nav className="hidden sm:inline">
          <ul className="flex flex-row items-center gap-2 text-lg">
            <Link href="#">
              <li>Aplikacje Webowe</li>
            </Link>
            <p>·</p>
            <Link href="#">
              <li>Startupy</li>
            </Link>
            <p>·</p>
            <Link href="#">
              <Image src="/discord.svg" alt="" width={30} height={30} />
            </Link>
            <p>·</p>
            <Link href="#">
              <Image src="/github.svg" alt="" width={30} height={30} />
            </Link>
          </ul>
        </nav>
        <button className="sm:hidden">
          <Image src="/hamburger.svg" alt="" width={42} height={42} />
        </button>
      </header>
      <section>
        <div className="">
          <div className="max-h-[300px] max-w-[416px] relative">
            <Image src="/cover.png" alt="" fill />
          </div>
          <div>
            <span></span>
            <span></span>
            <h2></h2>
            <p></p>
            <Link href="#"></Link>
          </div>
        </div>
      </section>
      <footer></footer>
    </main>
  )
}
