import Image from 'next/image'
import Link from 'next/link'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <main>
      <section>
        <div className="">
          <div className="max-h-[300px] max-w-[416px] relative">
            <Image src="/cover.png" alt="" fill />
          </div>
          <div>
            <span></span>
            <span></span>
            <h2></h2>
            <p></p>
            <Link href="#"></Link>
          </div>
        </div>
      </section>
      <footer></footer>
    </main>
  )
}
